{"name": "Успешная авторизация", "status": "broken", "statusDetails": {"message": "playwright._impl._errors.TimeoutError: Timeout 30000ms exceeded.\n=========================== logs ===========================\nwaiting for navigation to \"**/logged-in-successfully/\" until 'load'\n============================================================", "trace": "page = <Page url='https://practicetestautomation.com/practice-test-login/'>\n\n    @allure.title(\"Успешная авторизация\")\n    def test_successful_login(page):\n        login_page = LoginPage(page)\n        login_page.goto()\n        login_page.login('student', 'Password12')\n    \n        # Проверка: заголовок и URL\n>       page.wait_for_url(\"**/logged-in-successfully/\")\n\ntests\\test_login.py:15: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\playwright\\sync_api\\_generated.py:9145: in wait_for_url\n    self._sync(\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\playwright\\_impl\\_page.py:584: in wait_for_url\n    return await self._main_frame.wait_for_url(**locals_to_params(locals()))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\playwright\\_impl\\_frame.py:235: in wait_for_url\n    async with self.expect_navigation(\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\playwright\\_impl\\_event_context_manager.py:33: in __aexit__\n    await self._future\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\n    async def continuation() -> Optional[Response]:\n>       event = await waiter.result()\n                ^^^^^^^^^^^^^^^^^^^^^\nE       playwright._impl._errors.TimeoutError: Timeout 30000ms exceeded.\nE       =========================== logs ===========================\nE       waiting for navigation to \"**/logged-in-successfully/\" until 'load'\nE       ============================================================\n\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\playwright\\_impl\\_frame.py:209: TimeoutError"}, "attachments": [{"name": "screenshot", "source": "122d9c59-b480-4115-88a2-302d2dded106-attachment.png", "type": "image/png"}], "start": 1753825483913, "stop": 1753825520221, "uuid": "660c97c1-4c77-4e96-ab6f-044d1c0e2927", "historyId": "1cf440d643f6d7c25a856fa2d6115610", "testCaseId": "1cf440d643f6d7c25a856fa2d6115610", "fullName": "login_project.tests.test_login#test_successful_login", "labels": [{"name": "parentSuite", "value": "login_project.tests"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "LAPTOP-0KQPRK2H"}, {"name": "thread", "value": "18252-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "login_project.tests.test_login"}], "titlePath": ["login_project", "tests", "test_login.py"]}